version: "3"

services:
  web:
    container_name: myapp
    restart: always
    build: .
    ports:
      - "5000:3001"
    links:
      - mongoService
    volumes:
      - .:/usr/src/app
  
  mongoService:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
